""" Constants """

TEAM_IDS = {
    1:["atl", "atlanta", "falcons"],
    2:["buf", "buffalo", "bills"],
    3:["chi", "chicago", "bears"],
    4:["cin", "cinncinati", "bengals"],
    5:["cle", "cleveland", "browns"],
    6:["dal", "dallas", "cowboys"],
    7:["den", "denver", "broncos"],
    8:["det", "detroit", "lions"],
    9:["gb", "green bay", "packers"],
    10:["ten", "tennessee", "titans"],
    11:["ind", "indianapolis", "colts"],
    12:["kc", "kansas city", "chiefs"],
    13:["lv", "las vegas", "oakland", "oak", "raiders"],
    14:["lar", "los angeles", "st. louis", "st louis", "rams", "stl"],
    15:["mia", "miami", "dolphins"],
    16:["min", "minnesota", "vikings"],
    17:["ne", "new england", "patriots"],
    18:["no", "new orleans", "saints"],
    19:["nyg", "new york", "giants"],
    20:["nyj", "new york", "jets"],
    21:["phi", "philadelphia", "eagles"],
    22:["ari", "arizona", "cardinals"],
    23:["pit", "pittsburgh", "steelers"],
    24:["lac", "sd", "los angeles", "san diego", "chargers"],
    25:["sf", "san francisco", "49ers"],
    26:["sea", "seattle", "seahawks"],
    27:["tb", "tampa bay", "buccaneers"],
    28:["wsh", "washington", "redskins", "football team"],
    29:["car", "carolina", "panthers"],
    30:["jax", "jacksonville", "jaguars"],
    33:["bal", "baltimore", "ravens"],
    34:["hou", "houston", "texans"]
}