""" Constants """

TEAMS_2_NUM = {
    "ATL": 1,
    "BUF": 2,
    "CHI": 3,
    "CIN": 4,
    "CLE": 5,
    "DAL": 6,
    "DEN": 7,
    "DET": 8,
    "GB": 9,
    "TEN": 10,
    "IND": 11,
    "KC": 12,
    "LV": 13,
    "LAR": 14,
    "MIA": 15,
    "MIN": 16,
    "NE": 17,
    "NO": 18,
    "NYG": 19,
    "NYJ": 20,
    "PHI": 21,
    "ARI": 22,
    "PIT": 23,
    "LAC": 24,
    "SF": 25,
    "SEA": 26,
    "TB": 27,
    "WSH": 28,
    "CAR": 29,
    "JAX": 30,
    "BAL": 33,
    "HOU": 34
}

ALT_NAMES = {
    "ATL": ["atlanta", "falcons"],
    "BUF": ["buffalo", "bills"],
    "CHI": ["chicago", "bears"],
    "CIN": ["cinncinati", "bengals"],
    "CLE": ["cleveland", "browns"],
    "DAL": ["dallas", "cowboys"],
    "DEN": ["denver", "broncos"],
    "DET": ["detroit", "lions"],
    "GB": ["green bay", "packers"],
    "TEN": ["tennessee", "titans"],
    "IND": ["indianapolis", "colts"],
    "KC": ["kansas city", "chiefs"],
    "LV": ["las vegas", "oakland", "oak", "raiders"],
    "LAR": ["los angeles", "st. louis", "st louis", "rams"],
    "MIA": ["miami", "dolphins"],
    "MIN": ["minnesota", "vikings"],
    "NE": ["new england", "patriots"],
    "NO": ["new orleans", "saints"],
    "NYG": ["new york", "giants"],
    "NYJ": ["new york", "jets"],
    "PHI": ["philadelphia", "eagles"],
    "ARI": ["arizona", "cardinals"],
    "PIT": ["pittsburgh", "steelers"],
    "LAC": ["los angeles", "san diego", "chargers"],
    "SF": ["san francisco", "49ers"],
    "SEA": ["seattle", "seahawks"],
    "TB": ["tampa bay", "buccaneers"],
    "WSH": ["washington", "redskins", "football team"],
    "CAR": ["carolina", "panthers"],
    "JAX": ["jacksonville", "jaguars"],
    "BAL": ["baltimore", "ravens"],
    "HOU": ["houston", "texans"]
}